package io.github.jhipster.application.domain.enumeration;

/**
 * The TipoOferta enumeration.
 */
public enum TipoOferta {
    ALIMENTACION, BEBIDAS, ARTE, ANTIGUEDADES, VEHICULOS, CASAHOGAR, COLECCION, DEPORTES, EDUCACION, IMAGEN, SONIDO, INFORMATICA, ELECTRONICA, INMOBILIARIA, JOYERIA, JUEGOS, JUGUETES, LIBROS, REVISTAS, COMICS, MUSICA, ROPA, CALZADO, SALUD, BELLEZA, SERVICIOS, MANOOBRA, TELEFONIA, TIEMPOLIBRE
}
